create schema Clube_do_livro;

create table LIVROS(
ID_LIVRO INT NOT NULL,
NOME_LIVRO VARCHAR(100) NOT NULL,
AUTORIA VARCHAR (100) NOT NULL,
EDITORA VARCHAR (100) NOT NULL,
CATEGORIA VARCHAR (100) NOT NULL,
PRECO DECIMAL (5,2) NOT NULL,

PRIMARY KEY(ID_LIVRO)
);

CREATE TABLE ESTOQUE (
ID_LIVRO INT NOT NULL,
QTD_ESTOQUE INT NOT NULL,
PRIMARY KEY(ID_LIVRO)
);

CREATE TABLE VENDAS(
ID_PEDIDO INT NOT NULL,
ID_VENDEDOR INT NOT NULL,
ID_LIVRO INT NOT NULL,
QTD_ESTOQUE INT NOT NULL,
DATA_VENDA DATE NOT NULL,
PRIMARY KEY(ID_VENDEDOR,ID_PEDIDO)
);

CREATE TABLE VENDEDORES(
ID_VENDEDOR INT NOT NULL,
NOME_VENDEDOR VARCHAR (100) NOT NULL,
PRIMARY KEY(ID_VENDEDOR)
);
ALTER TABLE ESTOQUE ADD CONSTRAINT CE_ESTOQUE_LIVROS
FOREIGN KEY (ID_LIVRO)
REFERENCES LIVRO(ID_LIVRO)
ON DELETE ON ACTION
ON UPDATE ON ACTION;
